# .github/workflows/build-and-deploy.yml
name: Build and Deploy Static Site

on:
  push:
    branches: [ main ]
  schedule:
    # Run weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch: # Allow manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sqlite3 pandas

    - name: Export database to JSON
      run: |
        python scripts/db-to-json-export.py --db data/databases/holreg_research.db --output site/data

    - name: Generate static pages
      run: |
        python scripts/static-page-generator.py --data site/data --output site

    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: './site'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2

  # Optional: Create a release with the JSON data
  create-data-release:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    if: github.event_name == 'push' && contains(github.event.head_commit.message, '[release]')
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Export database to JSON
      run: |
        python scripts/db-to-json-export.py --db data/databases/holreg_research.db --output export

    - name: Create ZIP archive
      run: |
        zip -r hollywood-adaptations-data.zip export/

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: data-${{ github.run_number }}
        release_name: Data Export ${{ github.run_number }}
        body: |
          Automated data export from the Hollywood Adaptations database.
          
          This release contains JSON files with:
          - Film data
          - Author information
          - Controlled vocabulary
          - Theme analysis
          
          Generated on: ${{ github.event.head_commit.timestamp }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./hollywood-adaptations-data.zip
        asset_name: hollywood-adaptations-data.zip
        asset_content_type: application/zip